# Generated by Django 6.0.7 on 2026-09-09 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_turno', models.DateField(verbose_name='Fecha de Turno')),
                ('jornada', models.CharField(choices=[('Mañana', 'Mañana (07:00 - 13:00)'), ('Tarde', 'Tarde (13:00 - 19:00)'), ('Noche', 'Noche (19:00 - 07:00)'), ('24 Horas', '24 Horas')], default='Mañana', max_length=50, verbose_name='Jornada')),
                ('fecha_devolucion', models.DateField(verbose_name='Fecha de Devolución')),
                ('jornada_devolucion', models.CharField(choices=[('Mañana', 'Mañana (07:00 - 13:00)'), ('Tarde', 'Tarde (13:00 - 19:00)'), ('Noche', 'Noche (19:00 - 07:00)'), ('24 Horas', '24 Horas')], default='Mañana', max_length=50, verbose_name='Jornada de Devolución')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo u Observaciones')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('reemplazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Nombre del Reemplazo')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Nombre del Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de Cambio de Turno',
                'verbose_name_plural': 'Solicitudes de Cambio de Turnos',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
