# Generated by Django 6.0.7 on 2026-09-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solicitudcambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcambio',
            name='jornada',
            field=models.CharField(choices=[('N', 'N - DE 07:00 P.M A 07:00 A.M (NOCHE - 12 HRS)'), ('C', 'C - DE 07:00 A.M A 07:00 P.M (CORRIDO 12 HRS)'), ('C1', 'C1 - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('C2', 'C2 - DE 07:00 A.M A 01:00 P.M Y DE 02:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('M', 'M - DE 07:00 A.M A 01:00 P.M (MAÑANA - 6 HRS)'), ('T', 'T - DE 01:00 P.M A 07:00 P.M (TARDE - 6 HRS)'), ('T9', 'T9 - DE 01:00 P.M A 09:00 P.M (TARDE - 8 HRS)'), ('H', 'H - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 04:00 P.M (ADMINISTRATIVO - 8 HRS)'), ('D', 'D - DESCANSO'), ('L', 'L - LIBRE'), ('LC', 'LC - LIBRE CUMPLEAÑOS (8 HORAS)'), ('ME', 'ME - MAÑANA EDUCATIVA (6 HRS)'), ('TE', 'TE - TARDE EDUCATIVA (6 HRS)')], default='M', max_length=50, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='jornada_devolucion',
            field=models.CharField(choices=[('N', 'N - DE 07:00 P.M A 07:00 A.M (NOCHE - 12 HRS)'), ('C', 'C - DE 07:00 A.M A 07:00 P.M (CORRIDO 12 HRS)'), ('C1', 'C1 - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('C2', 'C2 - DE 07:00 A.M A 01:00 P.M Y DE 02:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('M', 'M - DE 07:00 A.M A 01:00 P.M (MAÑANA - 6 HRS)'), ('T', 'T - DE 01:00 P.M A 07:00 P.M (TARDE - 6 HRS)'), ('T9', 'T9 - DE 01:00 P.M A 09:00 P.M (TARDE - 8 HRS)'), ('H', 'H - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 04:00 P.M (ADMINISTRATIVO - 8 HRS)'), ('D', 'D - DESCANSO'), ('L', 'L - LIBRE'), ('LC', 'LC - LIBRE CUMPLEAÑOS (8 HORAS)'), ('ME', 'ME - MAÑANA EDUCATIVA (6 HRS)'), ('TE', 'TE - TARDE EDUCATIVA (6 HRS)')], default='M', max_length=50, verbose_name='Jornada de Devolución'),
        ),
    ]
