# Generated by Django 5.2.17 on 2026-09-11 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_solicitudcambio_jornada_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcambio',
            name='fecha_devolucion_2',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución 2'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='jornada_devolucion_2',
            field=models.CharField(blank=True, choices=[('N', 'N - DE 07:00 P.M A 07:00 A.M (NOCHE - 12 HRS)'), ('C', 'C - DE 07:00 A.M A 07:00 P.M (CORRIDO 12 HRS)'), ('C1', 'C1 - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('C2', 'C2 - DE 07:00 A.M A 01:00 P.M Y DE 02:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('M', 'M - DE 07:00 A.M A 01:00 P.M (MAÑANA - 6 HRS)'), ('T', 'T - DE 01:00 P.M A 07:00 P.M (TARDE - 6 HRS)'), ('T9', 'T9 - DE 01:00 P.M A 09:00 P.M (TARDE - 8 HRS)'), ('H', 'H - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 04:00 P.M (ADMINISTRATIVO - 8 HRS)'), ('D', 'D - DESCANSO'), ('L', 'L - LIBRE'), ('LC', 'LC - LIBRE CUMPLEAÑOS (8 HORAS)'), ('ME', 'ME - MAÑANA EDUCATIVA (6 HRS)'), ('TE', 'TE - TARDE EDUCATIVA (6 HRS)')], max_length=50, null=True, verbose_name='Jornada de Devolución 2'),
        ),
        migrations.AddField(
            model_name='solicitudcambio',
            name='reemplazo_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_recibidas_2', to=settings.AUTH_USER_MODEL, verbose_name='Nombre del Reemplazo 2 (Devolución 2)'),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='fecha_devolucion',
            field=models.DateField(verbose_name='Fecha de Devolución 1'),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='jornada_devolucion',
            field=models.CharField(choices=[('N', 'N - DE 07:00 P.M A 07:00 A.M (NOCHE - 12 HRS)'), ('C', 'C - DE 07:00 A.M A 07:00 P.M (CORRIDO 12 HRS)'), ('C1', 'C1 - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('C2', 'C2 - DE 07:00 A.M A 01:00 P.M Y DE 02:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('M', 'M - DE 07:00 A.M A 01:00 P.M (MAÑANA - 6 HRS)'), ('T', 'T - DE 01:00 P.M A 07:00 P.M (TARDE - 6 HRS)'), ('T9', 'T9 - DE 01:00 P.M A 09:00 P.M (TARDE - 8 HRS)'), ('H', 'H - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 04:00 P.M (ADMINISTRATIVO - 8 HRS)'), ('D', 'D - DESCANSO'), ('L', 'L - LIBRE'), ('LC', 'LC - LIBRE CUMPLEAÑOS (8 HORAS)'), ('ME', 'ME - MAÑANA EDUCATIVA (6 HRS)'), ('TE', 'TE - TARDE EDUCATIVA (6 HRS)')], default='M', max_length=50, verbose_name='Jornada de Devolución 1'),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='reemplazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Nombre del Reemplazo 1'),
        ),
    ]
