# Generated by Django 5.2.17 on 2026-09-11 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solicitudcambio_fecha_devolucion_2_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre del Área')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('administradores', models.ManyToManyField(blank=True, related_name='areas_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Administradores del Área')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='core.area', verbose_name='Área'),
        ),
        migrations.CreateModel(
            name='TurnoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Turno')),
                ('jornada', models.CharField(choices=[('N', 'N - DE 07:00 P.M A 07:00 A.M (NOCHE - 12 HRS)'), ('C', 'C - DE 07:00 A.M A 07:00 P.M (CORRIDO 12 HRS)'), ('C1', 'C1 - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('C2', 'C2 - DE 07:00 A.M A 01:00 P.M Y DE 02:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('M', 'M - DE 07:00 A.M A 01:00 P.M (MAÑANA - 6 HRS)'), ('T', 'T - DE 01:00 P.M A 07:00 P.M (TARDE - 6 HRS)'), ('T9', 'T9 - DE 01:00 P.M A 09:00 P.M (TARDE - 8 HRS)'), ('H', 'H - DE 07:00 A.M A 12:00 M Y DE 01:00 P.M A 04:00 P.M (ADMINISTRATIVO - 8 HRS)'), ('D', 'D - DESCANSO'), ('L', 'L - LIBRE'), ('LC', 'LC - LIBRE CUMPLEAÑOS (8 HORAS)'), ('ME', 'ME - MAÑANA EDUCATIVA (6 HRS)'), ('TE', 'TE - TARDE EDUCATIVA (6 HRS)')], max_length=50, verbose_name='Jornada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_programados', to='core.area', verbose_name='Área')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Programado Por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Empleado')),
            ],
            options={
                'verbose_name': 'Turno de Área',
                'verbose_name_plural': 'Turnos de Área',
                'ordering': ['fecha', 'usuario'],
            },
        ),
    ]
