# Generated by Django 5.2.17 on 2026-09-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_area_profile_area_turnoarea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcambio',
            name='jornada',
            field=models.CharField(choices=[('N', 'N - DE 06:00 P.M A 06:00 A.M (NOCHE 12H)'), ('C', 'C - DE 06:00 A.M A 06:00 P.M (CORRIDO 11 HRS)'), ('C1', 'C1 - DE 08:00 A.M A 06:00 P.M (CORRIDO 10 HRS)'), ('C2', 'C2 - DE 07:00 A.M A 01:00 P.M Y DE 02:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('H', 'H - DE 08:00 A.M A 12:00 M Y DE 01:00 P.M A 05:00 P.M (ADMINISTRATIVO)'), ('N1', 'N1 - DE 06:00 P.M A 12:00 P.M Y DE 01:00 A.M A 06:00 A.M (NOCHE 11H)'), ('M4', 'M4 - DE 08:00 A.M A 12:00 P.M (4 HORAS MAÑANA)'), ('M', 'M - DE 07:00 A.M A 01:00 P.M (MAÑANA 6 HRS)'), ('T', 'T - DE 01:00 P.M A 07:00 P.M (TARDE 6 HRS)'), ('T9', 'T9 - DE 01:00 P.M A 09:00 P.M (TARDE 8 HRS)'), ('LM', 'LM - LICENCIA MATERNIDAD'), ('D', 'D - DESCANSO'), ('L', 'L - LIBRE'), ('LC', 'LC - LIBRE CUMPLEAÑOS'), ('ME', 'ME - MAÑANA EDUCATIVA'), ('TE', 'TE - TARDE EDUCATIVA'), ('V', 'V - VACACIONES')], default='M', max_length=50, verbose_name='Jornada'),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='jornada_devolucion',
            field=models.CharField(choices=[('N', 'N - DE 06:00 P.M A 06:00 A.M (NOCHE 12H)'), ('C', 'C - DE 06:00 A.M A 06:00 P.M (CORRIDO 11 HRS)'), ('C1', 'C1 - DE 08:00 A.M A 06:00 P.M (CORRIDO 10 HRS)'), ('C2', 'C2 - DE 07:00 A.M A 01:00 P.M Y DE 02:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('H', 'H - DE 08:00 A.M A 12:00 M Y DE 01:00 P.M A 05:00 P.M (ADMINISTRATIVO)'), ('N1', 'N1 - DE 06:00 P.M A 12:00 P.M Y DE 01:00 A.M A 06:00 A.M (NOCHE 11H)'), ('M4', 'M4 - DE 08:00 A.M A 12:00 P.M (4 HORAS MAÑANA)'), ('M', 'M - DE 07:00 A.M A 01:00 P.M (MAÑANA 6 HRS)'), ('T', 'T - DE 01:00 P.M A 07:00 P.M (TARDE 6 HRS)'), ('T9', 'T9 - DE 01:00 P.M A 09:00 P.M (TARDE 8 HRS)'), ('LM', 'LM - LICENCIA MATERNIDAD'), ('D', 'D - DESCANSO'), ('L', 'L - LIBRE'), ('LC', 'LC - LIBRE CUMPLEAÑOS'), ('ME', 'ME - MAÑANA EDUCATIVA'), ('TE', 'TE - TARDE EDUCATIVA'), ('V', 'V - VACACIONES')], default='M', max_length=50, verbose_name='Jornada de Devolución 1'),
        ),
        migrations.AlterField(
            model_name='solicitudcambio',
            name='jornada_devolucion_2',
            field=models.CharField(blank=True, choices=[('N', 'N - DE 06:00 P.M A 06:00 A.M (NOCHE 12H)'), ('C', 'C - DE 06:00 A.M A 06:00 P.M (CORRIDO 11 HRS)'), ('C1', 'C1 - DE 08:00 A.M A 06:00 P.M (CORRIDO 10 HRS)'), ('C2', 'C2 - DE 07:00 A.M A 01:00 P.M Y DE 02:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('H', 'H - DE 08:00 A.M A 12:00 M Y DE 01:00 P.M A 05:00 P.M (ADMINISTRATIVO)'), ('N1', 'N1 - DE 06:00 P.M A 12:00 P.M Y DE 01:00 A.M A 06:00 A.M (NOCHE 11H)'), ('M4', 'M4 - DE 08:00 A.M A 12:00 P.M (4 HORAS MAÑANA)'), ('M', 'M - DE 07:00 A.M A 01:00 P.M (MAÑANA 6 HRS)'), ('T', 'T - DE 01:00 P.M A 07:00 P.M (TARDE 6 HRS)'), ('T9', 'T9 - DE 01:00 P.M A 09:00 P.M (TARDE 8 HRS)'), ('LM', 'LM - LICENCIA MATERNIDAD'), ('D', 'D - DESCANSO'), ('L', 'L - LIBRE'), ('LC', 'LC - LIBRE CUMPLEAÑOS'), ('ME', 'ME - MAÑANA EDUCATIVA'), ('TE', 'TE - TARDE EDUCATIVA'), ('V', 'V - VACACIONES')], max_length=50, null=True, verbose_name='Jornada de Devolución 2'),
        ),
        migrations.AlterField(
            model_name='turnoarea',
            name='jornada',
            field=models.CharField(choices=[('N', 'N - DE 06:00 P.M A 06:00 A.M (NOCHE 12H)'), ('C', 'C - DE 06:00 A.M A 06:00 P.M (CORRIDO 11 HRS)'), ('C1', 'C1 - DE 08:00 A.M A 06:00 P.M (CORRIDO 10 HRS)'), ('C2', 'C2 - DE 07:00 A.M A 01:00 P.M Y DE 02:00 P.M A 07:00 P.M (CORRIDO 11 HRS)'), ('H', 'H - DE 08:00 A.M A 12:00 M Y DE 01:00 P.M A 05:00 P.M (ADMINISTRATIVO)'), ('N1', 'N1 - DE 06:00 P.M A 12:00 P.M Y DE 01:00 A.M A 06:00 A.M (NOCHE 11H)'), ('M4', 'M4 - DE 08:00 A.M A 12:00 P.M (4 HORAS MAÑANA)'), ('M', 'M - DE 07:00 A.M A 01:00 P.M (MAÑANA 6 HRS)'), ('T', 'T - DE 01:00 P.M A 07:00 P.M (TARDE 6 HRS)'), ('T9', 'T9 - DE 01:00 P.M A 09:00 P.M (TARDE 8 HRS)'), ('LM', 'LM - LICENCIA MATERNIDAD'), ('D', 'D - DESCANSO'), ('L', 'L - LIBRE'), ('LC', 'LC - LIBRE CUMPLEAÑOS'), ('ME', 'ME - MAÑANA EDUCATIVA'), ('TE', 'TE - TARDE EDUCATIVA'), ('V', 'V - VACACIONES')], max_length=50, verbose_name='Jornada'),
        ),
    ]
