# Generated by Django 5.2.17 on 2026-09-12 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solicitudcambio_coordinador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código del Turno/Jornada')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción / Horario')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo (Ej. NOCHE, CORRIDO, DESCANSO)')),
                ('horas', models.IntegerField(default=0, verbose_name='Horas Equivalentes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Jornada / Turno',
                'verbose_name_plural': 'Jornadas / Turnos',
                'ordering': ['codigo'],
            },
        ),
    ]
