# Generated by Django 5.2.17 on 2026-09-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jornada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcambio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente Coordinador'), ('PENDIENTE_GH', 'Pendiente Gestión Humana'), ('ACEPTADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
