# Generated by Django 5.2.17 on 2026-09-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_solicitudcambio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcambio',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE_REEMPLAZO', 'Pendiente por Compañero'), ('PENDIENTE_COORDINADOR', 'Pendiente por Coordinador'), ('PENDIENTE_GH', 'Pendiente por Gestión Humana'), ('ACEPTADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE_REEMPLAZO', max_length=30, verbose_name='Estado'),
        ),
    ]
